#spring:
#  profiles:
#    active: dev
server:
  port: 8080
cupSize : DEV
age : 18
girl :
  cupSize : DEV
  age : 18
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/77_mybatis
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
